version: '3.8'

services:
  # Servicio del backend
  backend:
    build: ./api
    container_name: zombie-simulation-backend
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - ./src:/app/src
    environment:
      - DEBUG=1
    networks:
      - zombie-network

  # Servicio del frontend
  frontend:
    build: ./frontend
    container_name: zombie-simulation-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - zombie-network

networks:
  zombie-network:
    driver: bridge 