version: '3.8'

services:
  zombies-iot-simulation:
    build: .
    container_name: zombies-iot-simulation
    volumes:
      - ./logs:/app/logs
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    # En caso de que se expanda a una aplicación web o API
    ports:
      - "8000:8000" 